### ISSUE TITLE
Pass form data between requests

### ISSUE THREAD

**Issue by joeholdcroft** [mothership-ec/cog#260]
On the `Message\User` cogule we have had to implement some crazy session shit to retain form data because the register form is a sub-request, and it `POST`s to a separate page, which always redirects to referer.

So if an error means the form was not valid, all the user-entered data disappears because there's no `$_POST` data.

Thoughts on a global process for rectifying this? Is this all just one big antipattern? (Perhaps instead of using subrequests here, we should just make a `Register` form class available - see #137).

**Comment by thomasjthomasj** [comment]
Closing as use of the old form handler is deprecated
