### ISSUE TITLE
Migrations should error gracefully

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog#326]
When running migrations, it throws a fatal error if there is a migration in the database that it can't find the class for. This is a problem because if you have been working on a migration in a class, this will be in your database but won't necessarily be in your code base if you switch to another branch, and it's super annoying as you need to copy the row, delete it, run the migration, then add it back in

**Comment by kuiche** [comment]
I believe this is fixed with the migration load order changes.
