### ISSUE TITLE
xDebug maximum nesting level 100 reached

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog#421]
This is actually an issue with how Symfony Form and xDebug interact and so it's mostly a wontfix, but I'm making a note of it here in case the situation ever improves. For more information, check out the warning on this page: http://symfony.com/doc/current/cookbook/form/form_collections.html

**Comment by kuiche** [comment]
Closing as this is a known issue with the interaction between Symfony form and xDebug
