### ISSUE TITLE
Query Build `join()` and `leftJoin()` do not support `using` statements

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog#438]
Although I'm not sure the best way to implement it, since the `join()` and `leftJoin()` have the on statement as the second parameter, and there's  not an easy way that I can think of that maintains BC while still making the syntax nice.

What I would propose, though, is to add a forth parameter to determine whether it's an on statement or a using statement, like so:

```php
	public function join($alias, $onStatement, $table = null, $onStatement = true)
	{

	}

```

Then create the following methods:

+ `joinOn()`
+ `leftJoinOn()`
+ `joinUsing()`
+ `leftJoinUsing()`

which essentially alias the standard join functions, setting the forth parameter, allowing for more readability while maintaining BC

**Comment by kuiche** [comment]
Yes. That sounds like a good idea. Do we have `rightJoin` methods as well?
