### ISSUE TITLE
String generator seems to ignore regex when using generateNatively()

### ISSUE THREAD

**Issue by thomasjthomasj** [mothership-ec/cog#449]
Looking at the code it looks like it should work, but it evidently isn't as vouchers are being created using characters that are prohibited by the regex

**Comment by kuiche** [comment]
Something to do with this check? https://github.com/mothership-ec/cog/blob/develop/src/Security/StringGenerator.php#L192

**Comment by kuiche** [comment]
We could preg_match the char that is found here. https://github.com/mothership-ec/cog/blob/develop/src/Security/StringGenerator.php#L189. Or preg_match after generation with another loop.
