### ISSUE TITLE
Undefined Variable host

### ISSUE THREAD

**Issue by kuiche** [mothership-ec/cog#456]
When generating css assets, if there is anything of the form `url('/some/image')` (the starting slash is important) then an undefined variable exception will be thrown. "Undefined variable host".

https://github.com/mothership-ec/cog/blob/develop/src/AssetManagement/CssCoguleRewriteFilter.php#L38

**Comment by thomasjthomasj** [comment]
Hmm... I wonder what that variable is supposed to be
